# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 11:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutorial', '0002_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=256)),
                ('datePosted', models.DateTimeField(auto_now_add=True)),
                ('poster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kweets', to='tutorial.Account')),
            ],
        ),
    ]
